site_name: CodeCalc文档

# Page tree
nav:
  - Home: index.md
  - 运算符: operator.md
  - 函数: function.md
  - 字符串: string.md
  - 进制运算: radix_arithmetic.md
  - 时间计算: time_calc.md
  - 日期与时间戳: date_timestamp.md


theme:
    name: 'material'
    logo: logo.png
    favicon: logo.png

    font:
      text: Noto Serif Simplified Chinese
      code: Roboto Mono

    palette: 
      - scheme: default
        primary: deep purple
        accent: deep purple
        toggle:
          icon: material/toggle-switch-off
          name: Switch to dark mode

      - scheme: slate
        primary: blue grey
        accent: deep purple
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode


    features:
    - toc.integrate
    - navigation.top
    - navigation.tabs
    # - navigation.tabs.sticky
    # - content.tabs.link

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - nl2br
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true

plugins:
  - search
  - callouts
  - content-tabs
  - roamlinks
  - tags
  - glightbox


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
