name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-callouts mkdocs-content-tabs
      # - run: pip install mkdocs-rss-plugin
      # - run: pip install mkdocs-mermaid2-plugin
      # - run: pip install jinja2~=3.0 markdown~=3.2 mkdocs~=1.6 mkdocs-material-extensions~=1.3 pygments~=2.16 pymdown-extensions~=10.2
      # - run: pip install babel~=2.10 colorama~=0.4 paginate~=0.5 regex>=2022.4 requests~=2.26
      - run: mkdocs gh-deploy --force
